mybooks/chat/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$',  views.about, name='about'),
    url(r'^new/$', views.new_room, name='new_room'),
    url(r'^(?P<label>[\w-]{,50})/$', views.chat_room, name='chat_room'),
    url(r'^(?P<label>[\w-]{,50})/connect$', views.join_connect, name='join_connect'),
    url(r'^(?P<label>[\w-]{,50})/disconnect$', views.join_disconnect, name='join_disconnect'),
]

mybooks/mainapp/urls.py
from django.conf.urls import url
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/', views.register),
    url(r'^login/$', views.ajax_login, name='ajax_login'),
    url(r'^logout/$', views.ajax_logout, name='ajax_logout'),

    #   Authors
    url(r'^author/add_author/$', views.add_new_author, name='add_new_author'),
    url(r'^authors/$', views.show_authors, name='show_authors'),
    url(r'^authors/?(?P<key>[A-Za-z_]+)/$', views.show_authors_sorted, name='show_authors_sorted'),
    url(r'^authors/(?P<pk>[0-9]+)/$', views.get_author, name='get_author'),
    url(r'^authors/(?P<pk>[0-9]+)/change/$', views.change_author, name='change_author'),

    # Books
    url(r'^authors/(?P<pk>[0-9]+)/add_book/$', views.add_new_book, name='add_new_book'),
    url(r'^books/$', views.all_books, name='all_books'),
    url(r'^books/?(?P<key>[A-Za-z_]+)/$', views.all_books_sorted, name='all_books_sorted'),
    url(r'^books/(?P<pk>[0-9]+)/$', views.get_book, name='get_book'),
    url(r'^books/(?P<pk>[0-9]+)/evaluation/$', views.give_evaluation, name='give_evaluation'),
    url(r'^books/(?P<pk>[0-9]+)/status/$', views.give_status, name='give_status'),
    url(r'^books/(?P<pk>[0-9]+)/add_comment$', views.add_comment, name='add_comment'),
    url(r'^books/(?P<pk>[0-9]+)/add_another_author$', views.add_another_author, name='add_another_author'),
    url(r'^books/(?P<pk>[0-9]+)/change/$', views.change_book, name='change_book'),
    url(r'^books/find_another_author$', views.find_another_author, name='find_another_author'),

    #   User profile and user activities
    url(r'^user/my_tape$', views.my_tape, name='my_tape'),
    url(r'^user/subscriber_tape$', views.subscriber_tape, name='subscriber_tape'),
    url(r'^change/profile/$', views.change_profile, name='change_profile'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.profile, name='profile'),
    url(r'^profile/(?P<pk>[0-9]+)/subscribe$', views.subscribe, name='subscribe'),
    url(r'^profile/(?P<pk>[0-9]+)/unsubscribe$', views.unsubscribe, name='unsubscribe'),

    #   Additional options
    url(r'^export/$', views.export_books_from_profile, name='export_books_from_profile'),
    url(r'^heat_map_(?P<pk>[0-9]+)/$', views.get_statistics, name='get_statistics'),
    url(r'^search/$', views.search, name='search'),

    #   Test features
    url(r'^send_test_mail/$', views.send_test_mail, name='send_test_mail'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mybooks/mybooks/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('chat.urls')),
    url(r'^', include('mainapp.urls')),
]

mybooks/mainapp/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

def content_author_photo_name(instance, filename):
    return '/'.join(["media", "images", "author", str(instance.pk), "avatar"])

class Author(models.Model):
    name = models.CharField('author_name', max_length=200)
    original_name = models.CharField('original_name', max_length=200)
    country = models.CharField('country', max_length=40)
    birth_date  = models.CharField('birth_date', max_length=20)
    bigraphy = models.TextField('biography')
    photo_url = models.ImageField(upload_to=content_author_photo_name, default="media/images/author/default.png")
    rating = models.TextField('rating', default="-")

    def __str__(self):
        return self.name.encode('utf8')

    def update_rating(self):
        books = Book.objects.all().filter(author=self.pk)
        rating = 0
        counter = 0
        for i in books:
            if i.rating == "-":
                pass
            else:
                rating += float(i.rating)
                counter += 1
        if rating != 0:
            rating = float(rating) / counter
            rating = round(rating, 4)
            self.rating = rating

def content_book_cover_name(instance, filename):
    return '/'.join(["media", "images", "book", str(instance.pk), "cover"])

class Book(models.Model):
    name = models.CharField('book_name', max_length=100)
    original_name = models.CharField('original_name', max_length=100)
    book_type = models.CharField('book_type', max_length=50)
    publish_year = models.CharField('publish_year', max_length=5)
    genre = models.CharField('genre', max_length=30)
    annotation = models.TextField('annotation')
    author = models.ManyToManyField(Author)
    cover_url = models.ImageField(upload_to=content_book_cover_name, default="media/images/book/default.png")
    rating = models.TextField('rating', default="-")

    def __str__(self):
        return self.name.encode('utf8')

    def update_rating(self):
        messages = MessageReading.objects.all().filter(book_id=self.pk)
        rating = 0
        for i in messages:
            rating += i.evaluation
        rating = float(rating) / len(messages)
        rating = round(rating, 4)
        self.rating = rating


class MessageReading(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE)
    add_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    evaluation  = models.PositiveSmallIntegerField('evaluation', null=True)
    BOOK_STATE = (
        ('1', 'Читаю сейчас'),
        ('2', 'Прочитал'),
        ('3', 'Хочу прочитать'),
        ('4', 'Перестал читать'),
    )
    status = models.CharField(max_length=2, null=True, choices=BOOK_STATE, default=2)

    def __str__(self):
        return str(self.user_id)+str(self.book_id)

class UserActions(models.Model):
    request_user = models.ForeignKey(User,  on_delete=models.CASCADE, related_name='request_user')
    action_user = models.ForeignKey(User,  on_delete=models.CASCADE, related_name='action_user')
    add_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    action = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.request_user)+str(self.action_user)+str(self.action)

def content_avatar_name(instance, filename):
    return '/'.join(["media", "images", "user", str(instance.user_id.pk), "avatar"])

class Profile(models.Model):
    user_id = models.OneToOneField(User)
    age = models.IntegerField(null=True)
    avatar = models.ImageField(upload_to=content_avatar_name, default="media/images/user/default.png")

    def __str__(self):
        return str(self.user_id)

class Subscribe(models.Model):
    from_user = models.ForeignKey(User)
    to_user = models.ForeignKey(User, related_name="person_subscriber")

    def __str__(self):
        return str(self.from_user)

class CommentForBook(models.Model):
    book_id = models.ForeignKey(Book)
    user_id = models.ForeignKey(User)
    add_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    comment_field = models.TextField('comment')

    def __str__(self):
        return str(self.book_id)

mybooks/mainapp/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from mainapp.models import Author, Book,Profile

class RegistrationForm(forms.Form):

    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Username"), error_messages={ 'invalid': _("This value must contain only letters, numbers and underscores.") })
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password (again)"))

    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. Please try another one."))

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data


class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ('name', 'original_name', 'country', 'birth_date', 'bigraphy',)

class AuthorImageForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ('photo_url',)

class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('name', 'original_name', 'book_type', 'publish_year', 'genre', 'annotation',)

class BookImageForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('cover_url',)

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('age',)

class ProfileImageForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('avatar',)

mybooks/mainapp/templates/mainapp/add_author_information.html
{% extends "mainapp/base.html" %}
{% block content %}

    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="grid grid-fluid">
            <div class="row">
                <div class="col-2"></div>
                <div class="col-4"><h4>Выберите изображение</h4></div>
                <div class="col-4"><input id="image" name="image" type="file"></div>
                <div class="col-4"></div>
            </div>
            <div class="row">
                <div class="col-5"></div>
                <div class="col-4"><input type="submit" class="form-input" value="Отправить"></div>
                <div class="col-4"></div>
            </div>
        </div>
    </form>

{% endblock %}

mybooks/mainapp/templates/mainapp/add_book_information.html
{% extends "mainapp/base.html" %}
{% block content %}

    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="grid grid-fluid">
            <div class="row">
                <div class="col-2"></div>
                <div class="col-4"><h4>Выберите изображение</h4></div>
                <div class="col-4"><input id="image" name="image" type="file"></div>
                <div class="col-4"></div>
            </div>
            <div class="row">
                <div class="col-5"></div>
                <div class="col-4"><input type="submit" class="form-input" value="Отправить"></div>
                <div class="col-4"></div>
            </div>
        </div>
    </form>

{% endblock %}

mybooks/mainapp/templates/mainapp/add_new_author.html
{% extends "mainapp/base.html" %}
{% block content %}
<form method="POST">{% csrf_token %}
    <div class="grid grid-fluid">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><h1>Добавить автора:</h1></div>
            <div class="col-4"></div>
        </div>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><input id="name" name="name" type="text" required="" class="validate form-input" placeholder="Фамилия и имя"></div>
            <div class="col-4"></div>
        </div>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><input id="original_name" name="original_name" type="text" required="" class="validate form-input" placeholder="Фамилия и имя на оригинальном языке"></div>
            <div class="col-4"></div>
        </div>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><input id="country" name="country" type="text" required="" class="validate form-input" placeholder="Страна"></div>
            <div class="col-4"></div>
        </div>
            <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><input id="birth_date" name="birth_date" type="text" required="" class="validate form-input" placeholder="День рождения"></div>
            <div class="col-4"></div>
        </div>
            <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><input id="bigraphy" name="bigraphy" type="text" required="" class="validate form-input" placeholder="Биография"></div>
            <div class="col-4"></div>
        <div class="row">
            <div class="col-5"></div>
            <div class="col-4"><input type="submit" class="form-input" value="Отправить"></div>
            <div class="col-4"></div>
        </div>
    </div>
</form>

{% endblock %}

mybooks/mainapp/templates/mainapp/add_new_book.html
{% extends "mainapp/base.html" %}
{% block content %}
<form method="POST">{% csrf_token %}
    <div class="grid grid-fluid">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><h1>Добавить книгу:</h1></div>
            <div class="col-4"></div>
        </div>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><input id="name" name="name" type="text" required="" class="validate form-input" placeholder="Название"></div>
            <div class="col-4"></div>
        </div>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><input id="original_name" name="original_name" type="text" required="" class="validate form-input" placeholder="Оригинальное название"></div>
            <div class="col-4"></div>
        </div>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><input id="book_type" name="book_type" type="text" required="" class="validate form-input" placeholder="Тип книги"></div>
            <div class="col-4"></div>
        </div>
            <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><input id="publish_year" name="publish_year" type="text" required="" class="validate form-input" placeholder="Год публикации"></div>
            <div class="col-4"></div>
        </div>
            <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><input id="genre" name="genre" type="text" required="" class="validate form-input" placeholder="Жанр"></div>
            <div class="col-4"></div>
        </div>
            <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><input id="annotation" name="annotation" type="text" required="" class="validate form-input" placeholder="Аннотация"></div>
            <div class="col-4"></div>
        </div>
        <div class="row">
            <div class="col-5"></div>
            <div class="col-4"><input type="submit" class="form-input" value="Отправить"></div>
            <div class="col-4"></div>
        </div>
    </div>
</form>
{% endblock %}

mybooks/mainapp/templates/mainapp/book.html
{% extends "mainapp/base.html" %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/book.css">
{% endblock %}

{% block content %}
<a href={% url 'change_book' pk=book.pk %}><input type="button" class="form-input" value="Изменить данные"></a>
    <div class="grid grid-fluid">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-2"><img class="cover" src="{{ book.cover_url.url }}"/></div>
            <div class="col-3">
                <div class="row">
                    <div class="col-12 narrow">
                        <h4>{% for author in book.author.all %} <a href={% url 'get_author' pk=author.pk %}>{{ author.name }}</a>{% endfor %} </h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 narrow">
                        <h2>{{ book.name }} </h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 narrow">
                        <h5>{{ book.original_name }} </h5>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 narrow">
                        <h6>{{ book.book_type }}, {{ book.publish_year }} </h6>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 narrow">
                        <h6>Жанр: {{ book.genre }} </h6>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 narrow">
                        <h6>Рейтинг: {{ book.rating }} </h6>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <h4>Моя оценка:</h4>
                <ul class="rate" id="{{book.pk}}">
                    {% for i in range %}
                        {% if message.evaluation >= i %}
                        <li class="star pick" id="{{book.pk}}_{{i}}"></li>
                        {% else %}
                        <li class="star" id="{{book.pk}}_{{i}}"></li>
                        {% endif %}
                    {% endfor %}
                </ul>
                <hr>
                <h4>Текушая категория:</h4>
                <div id="categories">
                    {% if message.status == "1" %}
                        <div class="btn btn-color" id="{{book.pk}}_1">Читаю</div>
                    {% else %}
                        <div class="btn" id="{{book.pk}}_1">Читаю</div>
                    {% endif %}
                    {% if message.status == "2" %}
                        <div class="btn btn-color" id="{{book.pk}}_2">Прочитал</div>
                    {% else %}
                        <div class="btn" id="{{book.pk}}_2">Прочитал</div>
                    {% endif %}
                    {% if message.status == "3" %}
                        <div class="btn btn-color" id="{{book.pk}}_3">Хочу прочитать</div>
                    {% else %}
                        <div class="btn" id="{{book.pk}}_3">Хочу прочитать</div>
                    {% endif %}
                    {% if message.status == "4" %}
                        <div class="btn btn-color" id="{{book.pk}}_4">Бросил</div>
                    {% else %}
                        <div class="btn" id="{{book.pk}}_4">Бросил</div>
                    {% endif %}
                </div>
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col-2"></div>
            <div class="col-2">Аннотация:</div>
            <div class="col-6">
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col-10">{{ book.annotation }}</div>
                    <div class="col-1"></div>
                </div>
            </div>
            <div class="col-2"></div>
        </div>
    </div>

    {% if message_from_subs %}
    <div class="grid grid-fluid">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><h2>Оценки друзей:</h2></div>
            <div class="col-4"></div>
        </div>
        {% for message in message_from_subs %}
            <div class="row">
                <div class="col-3"></div>
                <div class="col-2">{{ message.user_id }}</div>
                <div class="col-2">{{ message.get_status_display }}</div>
                <div class="col-2">
                    <ul class="rate">
                        {% for i in range %}
                            {% if message.evaluation >= i %}
                            <li class="subs_star pick"></li>
                            {% else %}
                            <li class="subs_star"></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-3"></div>
            </div>
        {% endfor %}
    </div>
    {% endif %}


    <div class="grid grid-fluid">
        <div class="row">
            <div class="col-5"><a href={% url 'chat_room' label=book.pk %}><input type="button" class="form-input" value="Перейти в обсуждение"></a></div>
            <div class="col-7"><h2>Обзоры:</h2></div>
        </div>
        <div class="row">
        {% for comment in comments %}
            <div class="col-4">{{ comment.user_id }}</div>
            <div class="col-4">{{ comment.add_date}}</div>
            <div class="col-4">{{ comment.comment_field }}</div>
        {% endfor %}
        </div>
    </div>

<form method="POST">{% csrf_token %}
    <div class="grid grid-fluid">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><h3>Добавить обзор:</h3></div>
            <div class="col-4"></div>
        </div>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"><input id="id_add_comment" name="comment" type="text" required="" class="validate form-input" placeholder="Ваш обзор"></div>
            <div class="col-4"></div>
        <div class="row">
            <div class="col-5"></div>
            <div class="col-4"><input type="button" class="form-input" value="Отправить" id="ajax_add_comment"></div>
            <div class="col-4"></div>
        </div>
    </div>
</form>

<a href="#win2"><input type="button" class="form-input" value="Добавить автора"></a>


    <a href="#x" class="overlay" id="win2"></a>
    <div class="popup">
        <div class="grid grid-fluid">
            <h4>Добавить еще одного автора:</h4>
            <div class="row">
                <div class="col-2"></div>
                <div class="col-10">
                    <input id="id_author" name="id_author" type="text" required="" class="validate form-input" placeholder="ID автора">
                </div>
                <div class="col-2"></div>
            </div>
            <div class="row">
                <div class="col-5"></div>
                <div class="col-7">
                    <input type="button" class="form-input" value="Добавить" id="post_another_author">
                </div>
            </div>
        </div>
                    <hr>
        <div class="grid grid-fluid">
            <h4>Введите имя автора:</h4>

            <div class="row">
                <div class="col-2"></div>
                <div class="col-10">
                    <input id="name_author" name="name_author" type="text" required="" class="validate form-input" placeholder="Имя автора">
                </div>
                <div class="col-2"></div>
            </div>
            <div class="row">
                <div class="col-5"></div>
                <div class="col-7">
                    <input type="button" class="form-input" value="Найти" id="find_author">
                </div>
            </div>
        </div>
        <div class="grid grid-fluid" id="found_authors">
            <h4>Список найденных авторов:</h4>
        </div>
        <a class="close"title="Закрыть" href="#close"></a>
    </div>


{% endblock %}

mybooks/mainapp/templates/mainapp/my_tape.html
{% extends "mainapp/base.html" %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/my_tape.css">
{% endblock %}


{% block content %}

    <div class="grid grid-fluid">
        <div class="row row_borrow">
            <div class="col-2"></div>
            <div class="col-8"><h1>Лента событий</h1></div>
            <div class="col-2"></div>
        </div>
        {% for action in actions %}
            <div class="row row_borrow">
                {% if action.request_user %}
                    <div class="col-2"></div>
                    <div class="col-2"><p>{{ action.add_date|date:"d M G:i" }}</p></div>
                    <div class="col-2"> <a href={% url 'profile' pk=action.request_user.pk %}>{{ action.request_user }}</a> </div>
                    <div class="col-2">{{ action.action }}</div>
                    <div class="col-2"><a href={% url 'profile' pk=action.action_user.pk %}>{{ action.action_user }}</a></div>
                    <div class="col-2"></div>
                {% elif action.comment_field %}
                    <div class="col-2"></div>
                    <div class="col-2"><p>{{ action.add_date|date:"d M G:i" }}</p></div>
                    <div class="col-2"> <a href={% url 'profile' pk=action.user_id.pk %}>{{ action.user_id }}</a> </div>
                    <div class="col-2"><p>add review</p></div>
                    <div class="col-2"><a href={% url 'get_book' pk=action.book_id.pk %}>{{ action.book_id }}</a></div>
                    <div class="col-2"></div>
                {% else %}
                    <div class="col-2"></div>
                    <div class="col-1"><p>{{ action.add_date|date:"d M G:i" }}</p></div>
                    <div class="col-1"><p>{{ action.get_status_display }}</p></div>
                    <div class="col-2">
                        {% for author in action.book_id.author.all %}
                            {% if not forloop.last %}
                            <a href={% url 'get_author' pk=author.pk %}>{{ author.name }}</a> |
                            {% else %}
                            <a href={% url 'get_author' pk=author.pk %}>{{ author.name }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="col-2">
                        <a href={% url 'get_book' pk=action.book_id.pk %}>{{ action.book_id }}</a>
                        <p class="small">{{ action.book_id.original_name  }}</p>
                    </div>

                    <div class="col-2">
                        <ul class="rate" id="{{action.book_id.pk}}">
                            {% for i in range %}
                                {% if action.evaluation >= i %}
                                <li class="star pick" id="{{action.book_id.pk}}_{{i}}"></li>
                                {% else %}
                                <li class="star" id="{{action.book_id.pk}}_{{i}}"></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-2"></div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

mybooks/mainapp/templates/mainapp/register.html
{% extends "mainapp/base.html" %}
{% block login_content %}
<!-- Регистрация -->
<div class="grid grid-fluid">
	<form method="post" action=".">{% csrf_token %}
		<div class="row">
			<div class="col-3"></div>
			<div class="col-3">
				<input id="id_username" name="username" type="text" required="" class="validate form-input" placeholder="Your login">
			</div>
			<div class="col-3">
				<input id="id_email" max_length="30" name="email" type="text" required="" class="validate form-input" placeholder="Your email">
			</div>
			<div class="col-3"></div>
		</div>

		<div class="row">
			<div class="col-3"></div>
			<div class="col-3">
				<input id="id_password1" max_length="30" name="password1" type="password" required="" class="validate form-input" placeholder="Your password">
			</div>
			<div class="col-3">
				<input id="id_password2" max_length="30" name="password2" type="password" required="" class="validate form-input" placeholder="Repeat password">
			</div>
			<div class="col-3"></div>
		</div>

		<div class="row">
			<div class="col-5"></div>
			<div class="col-7">
				<input type="submit" class="form-input" value="Register">
			</div>
		</div>
	</form>

</div>

{% endblock %}

mybooks/mainapp/templates/mainapp/subscribers.html
{% extends "mainapp/base.html" %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/my_tape.css">
{% endblock %}

{% block content %}

    <div class="grid grid-fluid">
        <div class="row row_borrow">
            <div class="col-2"></div>
            <div class="col-8"><h1>Друзья</h1></div>
            <div class="col-2"></div>
        </div>
        {% for action in actions %}
            <div class="row row_borrow">
                {% if action.request_user %}
                    <div class="col-2"></div>
                    <div class="col-1"><p>{{ action.add_date|date:"d M G:i" }}</p></div>
                    <div class="col-2"> <a href={% url 'profile' pk=action.request_user.pk %}>{{ action.request_user }}</a> </div>
                    <div class="col-2">{{ action.action }}</div>
                    <div class="col-2"><a href={% url 'profile' pk=action.action_user.pk %}>{{ action.action_user }}</a></div>
                    <div class="col-2"></div>
                {% elif action.comment_field %}
                    <div class="col-2"></div>
                    <div class="col-1"><p>{{ action.add_date|date:"d M G:i" }}</p></div>
                    <div class="col-2"> <a href={% url 'profile' pk=action.user_id.pk %}>{{ action.user_id }}</a> </div>
                    <div class="col-2"><p>add review</p></div>
                    <div class="col-2"><a href={% url 'get_book' pk=action.book_id.pk %}>{{ action.book_id }}</a></div>
                    <div class="col-2"></div>
                {% else %}
                    <div class="col-2"></div>
                    <div class="col-1"><p>{{ action.add_date|date:"d M G:i" }}</p></div>
                    <div class="col-1"><a href={% url 'profile' pk=action.user_id.pk %}>{{ action.user_id }}</a></p></div>
                    <div class="col-1"><p>{{ action.get_status_display }}</p></div>
                    <div class="col-2">
                        {% for author in action.book_id.author.all %}
                            {% if not forloop.last %}
                            <a href={% url 'get_author' pk=author.pk %}>{{ author.name }}</a> |
                            {% else %}
                            <a href={% url 'get_author' pk=author.pk %}>{{ author.name }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="col-2">
                        <a href={% url 'get_book' pk=action.book_id.pk %}>{{ action.book_id }}</a>
                        <p class="small">{{ action.book_id.original_name  }}</p>
                    </div>

                    <div class="col-2">
                        <ul class="rate" id="{{action.book_id.pk}}">
                            {% for i in range %}
                                {% if action.evaluation >= i %}
                                <li class="subs_star pick"></li>
                                {% else %}
                                <li class="subs_star"></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-2"></div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}